'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  Handwrite:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      handwrite:
        type: dataset
        with:
          ref: model-handwrite
    uses: script@v1
    with:
      script: |-
        pip install scipy==1.3.3
        pip install Pillow==6.2.1
        pip install sklearn
        pip install matplotlib
        python /inputs/repo/pretrainedmodel.py
      image: tensorflow/tensorflow:1.14.0-py3
